services:
  backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: ez-task-backend
    restart: unless-stopped
    networks:
      - mysql-network       
      - eztask-network

networks:
  eztask-network:
    external: true
  mysql-network:
    external: true